# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/payton/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    bluetooth \
    modem \
    abl \
    devcfg \
    dsp \
    fsg \
    hyp \
    keymaster \
    logo \
    prov \
    storsec \
    tz \
    xbl
